services:
  paintball_robot:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ros2_yolo_v8
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
      - ./build:/workspace/paintball-person-tracker/build
      - ./install:/workspace/paintball-person-tracker/install
      - ./log:/workspace/paintball-person-tracker/log
      - ./models:/workspace/paintball-person-tracker/models
      - ./src:/workspace/paintball-person-tracker/src
    environment:
      - DISPLAY=$DISPLAY
      - RCUTILS_COLORIZED_OUTPUT=1
      - NVIDIA_VISIBLE_DEVICES=all
      - LD_LIBRARY_PATH=/usr/local/cuda/lib:/usr/local/cuda/lib64
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - ROS_LOCALHOST_ONLY=1
      - ROS_DOMAIN_ID=42
      - USER_PASSWORD
    devices:
      - /dev/video0:/dev/video0
      - /dev/ttyACM0:/dev/ttyACM0
    network_mode: host
    command: source install/setup.zsh
    ipc: host
    tty: True
    privileged: true
